/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Assets
         * @description The configured universe, primary assets first.
         */
        get: operations["list_assets_api_v1_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{symbol}/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Bars
         * @description Stored bars in time order. Without `start`, the latest `limit` bars.
         */
        get: operations["get_bars_api_v1_assets__symbol__bars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Pipeline and data status. Always answers, even when the database is down.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssetOut */
        AssetOut: {
            /**
             * Asset Class
             * @enum {string}
             */
            asset_class: "crypto" | "stock";
            /**
             * History Start
             * Format: date
             */
            history_start: string;
            /** Is Primary */
            is_primary: boolean;
            /** Name */
            name: string;
            /** News Start */
            news_start: string | null;
            /** Slug */
            slug: string;
            /** Symbol */
            symbol: string;
            /** Trades Continuously */
            trades_continuously: boolean;
        };
        /** BarOut */
        BarOut: {
            /** Close */
            close: number;
            /** High */
            high: number;
            /** Is Outlier */
            is_outlier: boolean;
            /** Is Quote Only */
            is_quote_only: boolean;
            /** Low */
            low: number;
            /** Open */
            open: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Volume */
            volume: number;
        };
        /** BarsOut */
        BarsOut: {
            /** Bars */
            bars: components["schemas"]["BarOut"][];
            /** Count */
            count: number;
            /** Source */
            source: string | null;
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Database */
            database: boolean;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Last Sync */
            last_sync: string | null;
            quality: components["schemas"]["QualitySummary"];
            /** Series */
            series: components["schemas"]["SeriesStatus"][];
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "down";
            /** Stream Clients */
            stream_clients: number;
        };
        /**
         * LiveBar
         * @description A live one-minute bar pushed over `WS /stream`. Not stored.
         */
        LiveBar: {
            /** Close */
            close: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Open */
            open: number;
            /** Symbol */
            symbol: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * Type
             * @constant
             */
            type: "bar";
            /**
             * Volume
             * @default null
             */
            volume: number | null;
        };
        /**
         * LiveNews
         * @description A new article pushed over `WS /stream`.
         */
        LiveNews: {
            /** Id */
            id: number;
            /** Symbols */
            symbols: string[];
            /**
             * Type
             * @constant
             */
            type: "news";
        };
        /** QualitySummary */
        QualitySummary: {
            /** Failures */
            failures: number;
            /** Findings */
            findings: number;
            /** Last Run */
            last_run: string | null;
            /** Warnings */
            warnings: number;
        };
        /** SeriesStatus */
        SeriesStatus: {
            /** Bars */
            bars: number;
            /**
             * First Ts
             * Format: date-time
             */
            first_ts: string;
            /** Is Primary */
            is_primary: boolean;
            /** Lag Seconds */
            lag_seconds: number;
            /**
             * Last Ts
             * Format: date-time
             */
            last_ts: string;
            /** Missing Share */
            missing_share: number | null;
            /** Stale */
            stale: boolean;
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_assets_api_v1_assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"][];
                };
            };
        };
    };
    get_bars_api_v1_assets__symbol__bars_get: {
        parameters: {
            query?: {
                timeframe?: string;
                start?: string | null;
                end?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
}
