/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Assets
         * @description The configured universe, primary assets first.
         */
        get: operations["list_assets_api_v1_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{symbol}/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Bars
         * @description Stored bars in time order. Without `start`, the latest `limit` bars.
         */
        get: operations["get_bars_api_v1_assets__symbol__bars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{symbol}/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Calibration
         * @description How often the simulator's past ranges contained what happened.
         */
        get: operations["get_calibration_api_v1_assets__symbol__calibration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{symbol}/event-study": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event Study
         * @description Whether news tone has led price, followed it, or neither, with the evidence.
         */
        get: operations["get_event_study_api_v1_assets__symbol__event_study_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{symbol}/regime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Regime
         * @description The current market regime, its history, and how the model has measured.
         */
        get: operations["get_regime_api_v1_assets__symbol__regime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{symbol}/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Risk
         * @description Value at Risk and expected shortfall, with how often each limit has been broken.
         */
        get: operations["get_risk_api_v1_assets__symbol__risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{symbol}/sentiment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sentiment
         * @description News tone over time, the articles with the strongest tone, and the model's accuracy.
         */
        get: operations["get_sentiment_api_v1_assets__symbol__sentiment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{symbol}/simulation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Simulation
         * @description The latest stored simulator run: the outcome distribution at each horizon.
         */
        get: operations["get_simulation_api_v1_assets__symbol__simulation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{symbol}/simulation/level": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Simulation Level
         * @description Chances of ending beyond, and of touching, a price level. Counted from stored paths.
         */
        post: operations["post_simulation_level_api_v1_assets__symbol__simulation_level_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{symbol}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description The answers in brief, what changed this week, and a trust grade for each claim.
         */
        get: operations["get_summary_api_v1_assets__symbol__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{symbol}/track-record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Track Record
         * @description How forecasts logged on the day they were made have turned out since.
         */
        get: operations["get_track_record_api_v1_assets__symbol__track_record_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{symbol}/volatility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Volatility
         * @description The volatility forecast, past forecasts against what happened, and model scores.
         */
        get: operations["get_volatility_api_v1_assets__symbol__volatility_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Pipeline and data status. Always answers, even when the database is down.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio
         * @description The saved holdings and the assets that can be held.
         */
        get: operations["get_portfolio_api_v1_portfolio_get"];
        /**
         * Put Portfolio
         * @description Replace the holdings with these, and analyse them.
         */
        put: operations["put_portfolio_api_v1_portfolio_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis
         * @description Where the portfolio's risk comes from, its loss limits, and past episodes replayed.
         */
        get: operations["get_analysis_api_v1_portfolio_analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Portfolio
         * @description Replace the holdings with those in a CSV file's text, and analyse them.
         */
        post: operations["import_portfolio_api_v1_portfolio_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Analysis
         * @description Everything the Portfolio screen shows, as stored.
         */
        Analysis: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Limits */
            limits: components["schemas"]["LimitHorizon"][];
            /** Model Version */
            model_version: string;
            /** Positions */
            positions: components["schemas"]["Position"][];
            /** Stress */
            stress: components["schemas"]["StressResult"][];
            trust: components["schemas"]["Trusts"];
            /** Value */
            value: number;
            xray: components["schemas"]["Xray"];
        };
        /** ArticleOut */
        ArticleOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Headline */
            headline: string;
            /** Id */
            id: number;
            /** Score */
            score: number;
            /** Source */
            source: string;
            /** Topic */
            topic: string | null;
            /** Url */
            url: string | null;
        };
        /** AssetOut */
        AssetOut: {
            /**
             * Asset Class
             * @enum {string}
             */
            asset_class: "crypto" | "stock";
            /**
             * History Start
             * Format: date
             */
            history_start: string;
            /** Is Primary */
            is_primary: boolean;
            /** Name */
            name: string;
            /** News Start */
            news_start: string | null;
            /** Slug */
            slug: string;
            /** Symbol */
            symbol: string;
            /** Trades Continuously */
            trades_continuously: boolean;
        };
        /**
         * Backtest
         * @description How one method's limit held at one level. Every period is out of sample.
         */
        Backtest: {
            /** Breach Rate */
            breach_rate: number;
            /** Breaches */
            breaches: number;
            /** Clustering P Value */
            clustering_p_value: number | null;
            /** Expected Breaches */
            expected_breaches: number;
            /**
             * First Day
             * Format: date
             */
            first_day: string;
            /** Kupiec P Adjusted */
            kupiec_p_adjusted?: number | null;
            /** Kupiec P Value */
            kupiec_p_value: number | null;
            /**
             * Last Day
             * Format: date
             */
            last_day: string;
            /** Level */
            level: number;
            /** Method */
            method: string;
            /** N */
            n: number;
            /** Reliable */
            reliable: boolean;
        };
        /** BarOut */
        BarOut: {
            /** Close */
            close: number;
            /** High */
            high: number;
            /** Is Outlier */
            is_outlier: boolean;
            /** Is Quote Only */
            is_quote_only: boolean;
            /** Low */
            low: number;
            /** Open */
            open: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Volume */
            volume: number;
        };
        /** BarsOut */
        BarsOut: {
            /** Bars */
            bars: components["schemas"]["BarOut"][];
            /** Count */
            count: number;
            /** Source */
            source: string | null;
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
        };
        /** CalibrationOut */
        CalibrationOut: {
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Model Version */
            model_version: string;
            /** Rows */
            rows: components["schemas"]["CalibrationRowOut"][];
            /** Symbol */
            symbol: string;
        };
        /** CalibrationRowOut */
        CalibrationRowOut: {
            /** Conformal High */
            conformal_high?: number | null;
            /** Conformal Low */
            conformal_low?: number | null;
            /** Empirical */
            empirical: number;
            /** Empirical Conformal */
            empirical_conformal: number;
            /** Empirical High */
            empirical_high?: number | null;
            /** Empirical Low */
            empirical_low?: number | null;
            /**
             * First Origin
             * Format: date
             */
            first_origin: string;
            /** Horizon Days */
            horizon_days: number;
            /**
             * Last Origin
             * Format: date
             */
            last_origin: string;
            /** N */
            n: number;
            /** Nominal */
            nominal: number;
            /** Pinball Baseline */
            pinball_baseline: number;
            /** Pinball Model */
            pinball_model: number;
            /** Steps */
            steps: number;
        };
        /** ChangeOut */
        ChangeOut: {
            /** Text */
            text: string;
            /**
             * Topic
             * @enum {string}
             */
            topic: "state" | "swings" | "tone";
        };
        /** ClassifierScoreOut */
        ClassifierScoreOut: {
            /** Accuracy */
            accuracy: number;
            /** Accuracy High */
            accuracy_high?: number | null;
            /** Accuracy Low */
            accuracy_low?: number | null;
            /** Macro F1 */
            macro_f1: number;
            /** N */
            n: number;
        };
        /** CsvIn */
        CsvIn: {
            /** Csv */
            csv: string;
        };
        /** DirectionOut */
        DirectionOut: {
            /** Both Polar */
            both_polar: number;
            /** N */
            n: number;
            /** Opposite Rate */
            opposite_rate: number;
            /** Same Direction */
            same_direction: number | null;
        };
        /** DrawdownOut */
        DrawdownOut: {
            /** Depth */
            depth: number;
            /**
             * Peak Day
             * Format: date
             */
            peak_day: string;
            /** Recovered Day */
            recovered_day: string | null;
            /**
             * Trough Day
             * Format: date
             */
            trough_day: string;
        };
        /** EventPathOut */
        EventPathOut: {
            /** High */
            high: number[];
            /** Low */
            low: number[];
            /** Mean */
            mean: number[];
            /** N */
            n: number;
            /** Offsets */
            offsets: number[];
        };
        /** EventStudyOut */
        EventStudyOut: {
            baseline: components["schemas"]["EventPathOut"];
            /**
             * By Topic
             * @default []
             */
            by_topic: components["schemas"]["TopicVerdict"][];
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Days With News */
            days_with_news: number;
            /** First Day */
            first_day: string | null;
            /** Lags */
            lags: components["schemas"]["LagOut"][];
            /** Last Day */
            last_day: string | null;
            /** Min Events */
            min_events: number;
            /** N Events */
            n_events: number;
            /** N Negative */
            n_negative: number;
            /** N Positive */
            n_positive: number;
            negative: components["schemas"]["EventPathOut"];
            positive: components["schemas"]["EventPathOut"];
            /** Symbol */
            symbol: string;
            /** Tests In Family */
            tests_in_family?: number | null;
            /** Verdict */
            verdict: string;
        };
        /** Fall */
        Fall: {
            /** Depth */
            depth: number;
            /**
             * Peak Day
             * Format: date
             */
            peak_day: string;
            /**
             * Trough Day
             * Format: date
             */
            trough_day: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Database */
            database: boolean;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Last Sync */
            last_sync: string | null;
            quality: components["schemas"]["QualitySummary"];
            /** Series */
            series: components["schemas"]["SeriesStatus"][];
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "down";
            /** Stream Clients */
            stream_clients: number;
        };
        /** Holding */
        Holding: {
            /** Quantity */
            quantity: number;
            /** Symbol */
            symbol: string;
            /** Tag */
            tag?: ("core" | "satellite") | null;
        };
        /** HoldingRisk */
        HoldingRisk: {
            /** Daily Volatility */
            daily_volatility: number;
            /** Risk Share */
            risk_share: number;
            /** Symbol */
            symbol: string;
            /** Weight */
            weight: number;
        };
        /** HoldingsIn */
        HoldingsIn: {
            /** Holdings */
            holdings: components["schemas"]["Holding"][];
        };
        /** LagOut */
        LagOut: {
            /** Correlation */
            correlation: number;
            /** Lag */
            lag: number;
            /** N */
            n: number;
            /** Significant */
            significant: boolean;
        };
        /** LevelIn */
        LevelIn: {
            /** Horizon Days */
            horizon_days: number;
            /** Level */
            level: number;
        };
        /**
         * LevelOut
         * @description Two different questions about one price level, kept apart.
         */
        LevelOut: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Ends Above */
            ends_above: number;
            /** Ends Below */
            ends_below: number;
            /** Horizon Days */
            horizon_days: number;
            /** Level */
            level: number;
            /** N Paths */
            n_paths: number;
            /** Start Price */
            start_price: number;
            /** Steps */
            steps: number;
            /** Symbol */
            symbol: string;
            /** Touches */
            touches: number;
        };
        /**
         * Limit
         * @description One method's current limit at one level, and how its past limits held.
         */
        Limit: {
            backtest: components["schemas"]["Backtest"];
            /** Expected Shortfall */
            expected_shortfall: number;
            /** Method */
            method: string;
            /** Var */
            var: number;
        };
        /** LimitHorizon */
        LimitHorizon: {
            /** Horizon Days */
            horizon_days: number;
            /** Levels */
            levels: components["schemas"]["LimitLevel"][];
            /** Shown */
            shown: string;
            /** Steps */
            steps: number;
        };
        /** LimitLevel */
        LimitLevel: {
            /** Level */
            level: number;
            /** Methods */
            methods: components["schemas"]["Limit"][];
        };
        /**
         * LiveBar
         * @description A live one-minute bar pushed over `WS /stream`. Not stored.
         */
        LiveBar: {
            /** Close */
            close: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Open */
            open: number;
            /** Symbol */
            symbol: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * Type
             * @constant
             */
            type: "bar";
            /**
             * Volume
             * @default null
             */
            volume: number | null;
        };
        /**
         * LiveNews
         * @description A new article pushed over `WS /stream`.
         */
        LiveNews: {
            /** Id */
            id: number;
            /** Symbols */
            symbols: string[];
            /**
             * Type
             * @constant
             */
            type: "news";
        };
        /** OutlookHorizon */
        OutlookHorizon: {
            /** Expected Worst Drawdown */
            expected_worst_drawdown: number;
            /** Histogram Counts */
            histogram_counts: number[];
            /** Histogram Edges */
            histogram_edges: number[];
            /** Horizon Days */
            horizon_days: number;
            /** Intervals */
            intervals: components["schemas"]["OutlookRange"][];
            /** Mean Return */
            mean_return: number;
            /** Quantiles */
            quantiles: {
                [key: string]: number;
            };
            /** Steps */
            steps: number;
        };
        /**
         * OutlookRange
         * @description A central range of simulated prices, raw and after the conformal adjustment.
         */
        OutlookRange: {
            /** Adjusted High */
            adjusted_high: number | null;
            /** Adjusted Is Widest */
            adjusted_is_widest: boolean;
            /** Adjusted Low */
            adjusted_low: number | null;
            /** High */
            high: number;
            /** Level */
            level: number;
            /** Low */
            low: number;
        };
        /** PortfolioOut */
        PortfolioOut: {
            /** Holdings */
            holdings: components["schemas"]["Holding"][];
            /** Problem */
            problem?: string | null;
            /** Source */
            source: string | null;
            /** Supported */
            supported: components["schemas"]["SupportedAsset"][];
            /**
             * Unsupported
             * @default []
             */
            unsupported: components["schemas"]["Unsupported"][];
        };
        /** Position */
        Position: {
            /** Name */
            name: string;
            /** Price */
            price: number;
            /** Quantity */
            quantity: number;
            /** Symbol */
            symbol: string;
            /** Tag */
            tag: string | null;
            /** Value */
            value: number;
            /** Weight */
            weight: number;
        };
        /** QualitySummary */
        QualitySummary: {
            /** Failures */
            failures: number;
            /** Findings */
            findings: number;
            /** Last Run */
            last_run: string | null;
            /** Warnings */
            warnings: number;
        };
        /**
         * RegimeEvaluationOut
         * @description Walk-forward results: every figure is from days the model had not seen.
         */
        RegimeEvaluationOut: {
            /** Average Run Length */
            average_run_length: number;
            /** Baseline Log Density */
            baseline_log_density: number;
            /**
             * First Test Day
             * Format: date
             */
            first_test_day: string;
            /**
             * Last Test Day
             * Format: date
             */
            last_test_day: string;
            /** Model Log Density */
            model_log_density: number;
            /** N Days */
            n_days: number;
            /** Next Day Volatility */
            next_day_volatility: {
                [key: string]: number;
            };
            /** Volatility Is Ordered */
            volatility_is_ordered: boolean;
        };
        /** RegimeModelOut */
        RegimeModelOut: {
            /** Bic By States */
            bic_by_states: {
                [key: string]: number;
            };
            /** N Train */
            n_train: number;
            /**
             * Train End
             * Format: date
             */
            train_end: string;
            /**
             * Train Start
             * Format: date
             */
            train_start: string;
            /**
             * Trained At
             * Format: date-time
             */
            trained_at: string;
            /** Version */
            version: string;
        };
        /** RegimeOut */
        RegimeOut: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Days In State */
            days_in_state: number;
            evaluation: components["schemas"]["RegimeEvaluationOut"] | null;
            /** History */
            history: components["schemas"]["RegimePoint"][];
            /** Label */
            label: string;
            model: components["schemas"]["RegimeModelOut"];
            /** Probabilities */
            probabilities: {
                [key: string]: number;
            };
            /** Probability */
            probability: number;
            /** States */
            states: components["schemas"]["RegimeStateOut"][];
            /** Symbol */
            symbol: string;
        };
        /** RegimePoint */
        RegimePoint: {
            /** Label */
            label: string;
            /** Probability */
            probability: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
        /** RegimeStateOut */
        RegimeStateOut: {
            /** Label */
            label: string;
            /** Next States */
            next_states: {
                [key: string]: number;
            };
            /** Typical Daily Volatility */
            typical_daily_volatility: number;
            /** Typical Duration Days */
            typical_duration_days: number;
        };
        /** RiskHorizonOut */
        RiskHorizonOut: {
            /**
             * First Day
             * Format: date
             */
            first_day: string;
            /** Horizon Days */
            horizon_days: number;
            /**
             * Last Day
             * Format: date
             */
            last_day: string;
            /** Levels */
            levels: components["schemas"]["RiskLevelOut"][];
            /** Shown */
            shown: string;
            /** Steps */
            steps: number;
        };
        /** RiskLevelOut */
        RiskLevelOut: {
            /** Level */
            level: number;
            /** Methods */
            methods: components["schemas"]["RiskMethodOut"][];
        };
        /**
         * RiskMethodOut
         * @description One method's current limit at one level, and how its past limits held.
         */
        RiskMethodOut: {
            /** Breach Rate */
            breach_rate: number;
            /** Breach Rate High */
            breach_rate_high?: number | null;
            /** Breach Rate Low */
            breach_rate_low?: number | null;
            /** Breaches */
            breaches: number;
            /** Clustering P Value */
            clustering_p_value: number | null;
            /** Expected Breaches */
            expected_breaches: number;
            /** Expected Shortfall */
            expected_shortfall: number;
            /** Kupiec P Adjusted */
            kupiec_p_adjusted?: number | null;
            /** Kupiec P Value */
            kupiec_p_value: number | null;
            /** Method */
            method: string;
            /** N */
            n: number;
            /** Reliable */
            reliable: boolean;
            /** Var */
            var: number;
        };
        /** RiskOut */
        RiskOut: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Drawdowns */
            drawdowns: components["schemas"]["DrawdownOut"][];
            /** Horizons */
            horizons: components["schemas"]["RiskHorizonOut"][];
            /** Model Version */
            model_version: string;
            /** Symbol */
            symbol: string;
        };
        /**
         * SentimentAccuracyOut
         * @description How the tone model did on headlines labelled by hand.
         */
        SentimentAccuracyOut: {
            baseline?: components["schemas"]["ClassifierScoreOut"] | null;
            direction?: components["schemas"]["DirectionOut"] | null;
            /**
             * Fine Tuned
             * @default false
             */
            fine_tuned: boolean;
            /**
             * Held Out
             * @default false
             */
            held_out: boolean;
            /** Labelled By */
            labelled_by: string[];
            model: components["schemas"]["ClassifierScoreOut"];
            original?: components["schemas"]["ClassifierScoreOut"] | null;
            topics?: components["schemas"]["ClassifierScoreOut"] | null;
        };
        /** SentimentOut */
        SentimentOut: {
            accuracy: components["schemas"]["SentimentAccuracyOut"] | null;
            /** Articles 24H */
            articles_24h: number;
            /** Articles 7D */
            articles_7d: number;
            /** Articles In Window */
            articles_in_window: number;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Current */
            current: number | null;
            /** Daily */
            daily: components["schemas"]["SentimentPoint"][];
            /** Days With News */
            days_with_news: number;
            /** Model Version */
            model_version: string;
            /**
             * News Start
             * Format: date
             */
            news_start: string;
            /** Recent */
            recent: components["schemas"]["ArticleOut"][];
            /** Symbol */
            symbol: string;
            /** Topics */
            topics: components["schemas"]["TopicSummary"][];
        };
        /** SentimentPoint */
        SentimentPoint: {
            /** Article Count */
            article_count: number;
            /** Score Decayed */
            score_decayed: number | null;
            /** Score Mean */
            score_mean: number | null;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
        /** SeriesStatus */
        SeriesStatus: {
            /** Bars */
            bars: number;
            /**
             * First Ts
             * Format: date-time
             */
            first_ts: string;
            /** Is Primary */
            is_primary: boolean;
            /** Lag Seconds */
            lag_seconds: number;
            /**
             * Last Ts
             * Format: date-time
             */
            last_ts: string;
            /** Missing Share */
            missing_share: number | null;
            /** Stale */
            stale: boolean;
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
        };
        /** SimulationOut */
        SimulationOut: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Fan */
            fan: {
                [key: string]: number[];
            };
            /** Horizons */
            horizons: components["schemas"]["OutlookHorizon"][];
            /** Model Version */
            model_version: string;
            /** N Paths */
            n_paths: number;
            /** Seed */
            seed: number;
            /** Start Price */
            start_price: number;
            /** Symbol */
            symbol: string;
        };
        /** StressPart */
        StressPart: {
            /** Change */
            change: number;
            /** Contribution */
            contribution: number;
            /** Symbol */
            symbol: string;
        };
        /** StressResult */
        StressResult: {
            /** Available */
            available: boolean;
            /** Change */
            change?: number | null;
            /**
             * Covered Weight
             * @default 0
             */
            covered_weight: number;
            /** Deepest Fall */
            deepest_fall?: number | null;
            /**
             * End
             * Format: date
             */
            end: string;
            /**
             * Missing
             * @default []
             */
            missing: string[];
            /** Name */
            name: string;
            /**
             * Parts
             * @default []
             */
            parts: components["schemas"]["StressPart"][];
            /**
             * Start
             * Format: date
             */
            start: string;
            /** Worst Day */
            worst_day?: string | null;
            /** Worst Day Change */
            worst_day_change?: number | null;
        };
        /** SummaryNews */
        SummaryNews: {
            /** Articles 24H */
            articles_24h: number;
            /** Current */
            current: number | null;
            /** Verdict */
            verdict: string | null;
        };
        /**
         * SummaryOut
         * @description The top of a market page: the answers in brief, what changed, and how far to trust each.
         */
        SummaryOut: {
            /** Changes */
            changes: components["schemas"]["ChangeOut"][];
            news: components["schemas"]["SummaryNews"] | null;
            outlook: components["schemas"]["SummaryOutlook"] | null;
            risk: components["schemas"]["SummaryRisk"] | null;
            state: components["schemas"]["SummaryState"] | null;
            swings: components["schemas"]["SummarySwings"] | null;
            /** Symbol */
            symbol: string;
            trust: components["schemas"]["SummaryTrust"];
        };
        /** SummaryOutlook */
        SummaryOutlook: {
            /** High */
            high: number;
            /** Horizon Days */
            horizon_days: number;
            /** Level */
            level: number;
            /** Low */
            low: number;
            /** Start Price */
            start_price: number;
            /** Steps */
            steps: number;
        };
        /** SummaryRisk */
        SummaryRisk: {
            /** Horizon Days */
            horizon_days: number;
            /** Level */
            level: number;
            /** Limit */
            limit: number;
        };
        /** SummaryState */
        SummaryState: {
            /** Days In State */
            days_in_state: number;
            /** Label */
            label: string;
            /** Probability */
            probability: number;
        };
        /** SummarySwings */
        SummarySwings: {
            /** Forecast */
            forecast: number;
            /** Last Realised */
            last_realised: number | null;
        };
        /** SummaryTrust */
        SummaryTrust: {
            news: components["schemas"]["TrustOut"];
            outlook: components["schemas"]["TrustOut"];
            risk: components["schemas"]["TrustOut"];
            state: components["schemas"]["TrustOut"];
            swings: components["schemas"]["TrustOut"];
        };
        /** SupportedAsset */
        SupportedAsset: {
            /**
             * Asset Class
             * @enum {string}
             */
            asset_class: "crypto" | "stock";
            /** Name */
            name: string;
            /** Symbol */
            symbol: string;
        };
        /** TopicSummary */
        TopicSummary: {
            /** Article Count */
            article_count: number;
            /** Score Mean */
            score_mean: number;
            /** Topic */
            topic: string;
        };
        /** TopicVerdict */
        TopicVerdict: {
            /** Days With News */
            days_with_news: number;
            /** N Events */
            n_events: number;
            /** Topic */
            topic: string;
            /** Verdict */
            verdict: string;
        };
        /**
         * TrackRecordOut
         * @description Forecasts logged on the day they were made and scored afterwards. Not a backtest.
         */
        TrackRecordOut: {
            /** Recorded */
            recorded: number;
            /** Recording Since */
            recording_since: string | null;
            /** Resolved */
            resolved: number;
            /** Rows */
            rows: components["schemas"]["TrackRecordRow"][];
            /** Symbol */
            symbol: string;
        };
        /** TrackRecordRow */
        TrackRecordRow: {
            /** Expected Share */
            expected_share: number | null;
            /**
             * First As Of
             * Format: date-time
             */
            first_as_of: string;
            /** Forecast To Outcome */
            forecast_to_outcome: number | null;
            /** Held */
            held: number | null;
            /** Held High */
            held_high: number | null;
            /** Held Low */
            held_low: number | null;
            /** Held Share */
            held_share: number | null;
            /** Horizon Days */
            horizon_days: number;
            /** Key */
            key: string;
            /** Kind */
            kind: string;
            /**
             * Last As Of
             * Format: date-time
             */
            last_as_of: string;
            /** Recorded */
            recorded: number;
            /** Resolved */
            resolved: number;
        };
        /** Trust */
        Trust: {
            /**
             * Grade
             * @enum {string}
             */
            grade: "solid" | "fair" | "rough";
            /** Reason */
            reason: string;
        };
        /** TrustOut */
        TrustOut: {
            /**
             * Grade
             * @enum {string}
             */
            grade: "solid" | "fair" | "rough";
            /** Reason */
            reason: string;
        };
        /** Trusts */
        Trusts: {
            risk: components["schemas"]["Trust"];
            stress: components["schemas"]["Trust"];
            xray: components["schemas"]["Trust"];
        };
        /**
         * Unsupported
         * @description Something the source held that RADAR cannot use, and why.
         */
        Unsupported: {
            /** Reason */
            reason: string;
            /** Symbol */
            symbol: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VolatilityHorizonOut */
        VolatilityHorizonOut: {
            /**
             * First Day
             * Format: date
             */
            first_day: string;
            /** Forecast */
            forecast: number;
            /** History */
            history: components["schemas"]["VolatilityPoint"][];
            /** Horizon Days */
            horizon_days: number;
            /**
             * Last Day
             * Format: date
             */
            last_day: string;
            /** Last Realised */
            last_realised: number | null;
            /** N */
            n: number;
            /** Reason */
            reason: string;
            /** Scores */
            scores: components["schemas"]["VolatilityScoreOut"][];
            /** Shown */
            shown: string;
            /** Steps */
            steps: number;
        };
        /** VolatilityOut */
        VolatilityOut: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Horizons */
            horizons: components["schemas"]["VolatilityHorizonOut"][];
            /** Model Version */
            model_version: string;
            /** Symbol */
            symbol: string;
        };
        /** VolatilityPoint */
        VolatilityPoint: {
            /** Forecast */
            forecast: number;
            /** Realised */
            realised: number | null;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
        /** VolatilityScoreOut */
        VolatilityScoreOut: {
            /** Dm P Value Vs Har */
            dm_p_value_vs_har?: number | null;
            /** Model */
            model: string;
            /** Mse */
            mse: number;
            /** Qlike */
            qlike: number;
        };
        /** Xray */
        Xray: {
            /** Correlation */
            correlation: number[][];
            /** Daily Volatility */
            daily_volatility: number;
            deepest_fall: components["schemas"]["Fall"];
            /**
             * First Day
             * Format: date
             */
            first_day: string;
            /** Holdings */
            holdings: components["schemas"]["HoldingRisk"][];
            /**
             * Last Day
             * Format: date
             */
            last_day: string;
            /** N Days */
            n_days: number;
            /** Symbols */
            symbols: string[];
            /** Undiversified Volatility */
            undiversified_volatility: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_assets_api_v1_assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"][];
                };
            };
        };
    };
    get_bars_api_v1_assets__symbol__bars_get: {
        parameters: {
            query?: {
                timeframe?: string;
                start?: string | null;
                end?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calibration_api_v1_assets__symbol__calibration_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_study_api_v1_assets__symbol__event_study_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventStudyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_regime_api_v1_assets__symbol__regime_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegimeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_risk_api_v1_assets__symbol__risk_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sentiment_api_v1_assets__symbol__sentiment_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SentimentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_simulation_api_v1_assets__symbol__simulation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_simulation_level_api_v1_assets__symbol__simulation_level_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LevelIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LevelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_v1_assets__symbol__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_track_record_api_v1_assets__symbol__track_record_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackRecordOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_volatility_api_v1_assets__symbol__volatility_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolatilityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    get_portfolio_api_v1_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
        };
    };
    put_portfolio_api_v1_portfolio_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_api_v1_portfolio_analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"];
                };
            };
        };
    };
    import_portfolio_api_v1_portfolio_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CsvIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
